### ISSUE TITLE
Allow custom data to be passed and filtered

### ISSUE THREAD

**Issue by ghost** [jakiestfu/Shadow#1]
For example: user meta, post slugs, request URIs, etc. Store it as JSON, a whole new world of possibilities, happy campers.

**Comment by jakiestfu** [comment]
Storing it as json means I'd have to query the data, decode it, determine what is to be I incremented, reencode, then reinsert as opposed to a single incremental query. Plus with the data stored as it currently is, future operations may be applied such as "get post with most views", etc.

Am I missin something?

**Comment by jas-** [comment]
@idiot has a good point but only if your going to offload the database contents to a caching service such as memcache.

Persistent storage would be MySQL etc. using JSON serialized strings
Cached queries could be offloaded to a [memcache](http://memcached.org/) sever as an already parsed object

You can achieve that same results by generating a [view](http://dev.mysql.com/doc/refman/5.0/en/create-view.html) within MySQL (when using relational tables) for any data which is accesses consistently. This is good for joins and the like if you think that JSON objects aren't the way to go.

**Comment by ghost** [comment]
fuck it, use whatever storage method you want, but custom data would be amazeballs

**Comment by Idered** [comment]
You can either use refrigerator to store it or you might create additional table(id, item_id, meta_key, meta_value) to store separated JSON keys and values but it's a heavy solution. Additional custom_data field in one of existing tables is lighter solution thought not so efficient as separated table.

**Comment by jakiestfu** [comment]
@idiot Give an example of a use case in which you'd want to store custom data, and what would you do with it?

@Idered refrigerator?

**Comment by Idered** [comment]
@jakiestfu joke

**Comment by jakiestfu** [comment]
@Idered -_____- hehe

**Comment by Idered** [comment]
@jakiestfu nevermind :/

Example of custom data usage:
Track user IP, last visit, browser and use those data in session manager(example: [dA](http://i.imgur.com/BCrWTfU.png) or gmail sessions).

**Comment by jakiestfu** [comment]
@Idered Gotcha.

Here is an example of how data could be set instead of a count, I imagine you'd just drop the value as a second param in `attribute`

Setting

``` php
$shadow->type( "forum" )
       ->item( "thread" )
       ->attribute( $userID."_lastVisit", "the value to set" )
       ->track();
```

Getting

``` php
$shadow->type( "forum" )
       ->item( "thread" )
       ->attribute( $userID."_lastVisit" )
       ->get();
```

Removing

``` php
$shadow->type( "forum" )
       ->item( "thread" )
       ->attribute( $userID."_lastVisit", null )
       ->track();
```

@Idered, @idiot Does that sound right? @idiot Is this how you envisioned the data storing to work or did you have another idea?

**Comment by Idered** [comment]
I guess it's a good method. In my previous comment I've mentioned about table with `item_id` but binding value to user ID is more reasonable because we want to track user not item.

Accepted.

**Comment by jakiestfu** [comment]
@idiot @Idered @jas- 

I've added support for setting values, string and arrays. Also, I've renamed the `attribute` method to `meta`, it's much more... meta.

``` php
$shadow->type( "foo" )
       ->item( "bar" )
       ->meta( "hello", "world" )
       ->track();
```

and 

``` php
$shadow->type( "foo" )
       ->item( "bar" )
       ->meta( "hello", array( "Dayumn", "Noice!" ) )
       ->track();
```

whereas

``` php
$shadow->type( "foo" )
       ->item( "bar" )
       ->meta( "hello" )
       ->track();
```

would just track a count

@idiot Does that fulfill your request?

**Comment by ghost** [comment]
you're damn right it does
