### ISSUE TITLE
Optimize Schema

### ISSUE THREAD

**Issue by jakiestfu** [jakiestfu/Shadow#4]
Database Schema needs to be optimized as best as possible to account for the high query rate of the `shadow_objects` -> `operation`, `namespace`, `type`

<a href="https://github.com/jakiestfu/Shadow/blob/master/src/install.sql"><img src="http://i.imgur.com/9HKq4rC.png"></a.

I think I should change `operation` to an int to represent the appropriate types:
- 1: Unary
- 2: Binary
- 3: Multary

What about the rest of the schema? Anyone have any ideas? View the schema <a href="https://github.com/jakiestfu/Shadow/blob/master/src/install.sql">here</a>

**Comment by jas-** [comment]
I have created a new branch '[suggestions](https://github.com/jakiestfu/Shadow/blob/suggestions/)' which has an [updated schema](https://github.com/jakiestfu/Shadow/blob/suggestions/src/install.sql) for you to review.

**Comment by jakiestfu** [comment]
Thanks dude! c7a7bb4ea72cd9867e753d87d6a646311b37e0fc
